pipeline:
  build:
    image: openjdk:8
    commands:
      - chmod a+x gradlew  
      - ./gradlew prdWrapper build
    deploy:
      resources:
        limits:
          cpus: '0.2'
branches: ["master","dev4"]
