pipeline:
  build:
    image: openjdk:8
    commands:
      - chmod a+x gradlew  
      - ./gradlew build
    cpu_shares: 50
    
  publish:
    image: plugins/docker
    tag: 
     - ${DRONE_BUILD_NUMBER}   
branches: ["master","dev6"]
