language: java
jdk:
  - openjdk8
install: true
before_script:
  - chmod +x gradlew  
script:  
  - ./gradlew bootJar
  
deploy:
  provider: releases
  user: "xiaoqlster@gmail.com "
  password: "caohaofen057922"
  file: "rrrr.jar"
  skip_cleanup: true
